### ISSUE TITLE
Bug: Closer causing nil pointer dereference

### ISSUE THREAD

**Issue by Kleissner** [knieriem/odf#1]
Your code has 2 calls to `closer.Close`. However, when using the function `NewReader`, it supplies nil as closer, which then results in nil pointer dereference.

https://github.com/knieriem/odf/blob/cef5c6ac1ad424f6264986b2959259af8ceac33b/read.go#L43-L48

The fix is simple (2 times), check if `closer` is nil:

```go
func newFile(z *zip.Reader, closer io.Closer) (*File, error) {
	f := new(File)
	f.Reader = z
	mf, err := f.Open("mimetype")
	if err != nil {
		if closer != nil {
			closer.Close()
		}
```

**Comment by knieriem** [comment]
Thanks for pointing that out, and for suggesting the fix. Sorry for the late reply.
